apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../modules/audit/deploy/k8s/overlays/dev
  - ../../../modules/auth/deploy/k8s/overlays/dev
  - ../../../modules/queue/deploy/k8s/overlays/dev
