services:
  migrator:
    build:
      dockerfile: ./.images/migrator/Dockerfile
    container_name: migrator
    working_dir: /go/src
    volumes:
      - .:/go
    networks:
      - internal

  # audit
  audit-api:
    build:
      dockerfile: ./.images/audit/api.Dockerfile
    container_name: audit-api
    depends_on:
      audit-db: 
        condition: service_healthy
    networks:
      - internal
  audit-db:
    image: postgres:latest
    container_name: audit-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: audit
      POSTGRES_USER: audit
      POSTGRES_PASSWORD: audit
    volumes:
      - audit-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U audit -d audit"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal
  audit-worker:
    build:
      dockerfile: ./.images/audit/worker.Dockerfile
    container_name: audit-worker
    networks:
      - internal

  # auth
  auth-api:
    build:
      dockerfile: ./.images/auth/api.Dockerfile
    container_name: auth-api
    depends_on:
      auth-db: 
        condition: service_healthy
      auth_cache:
        condition: service_healthy
    networks:
      - internal
  auth-db:
    image: postgres:latest
    container_name: auth-db
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
    volumes:
      - auth-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth -d auth"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal
  auth_cache:
    image: redis:latest
    container_name: auth-cache
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

  # queue
  queue-api:
    build:
      dockerfile: ./.images/queue/Dockerfile
    container_name: queue-api
    networks:
      - internal

volumes:
  audit-db:
    driver: local
  auth-db:
    driver: local

networks:
  internal:
    driver: bridge
