services:
  # util go container
  gopher:
    build:
      dockerfile: ./.images/gopher/Dockerfile
    container_name: gopher
    working_dir: /go/src
    volumes:
      - .:/go/src

  migrator:
    build:
      dockerfile: ./.images/migrator/Dockerfile
    container_name: migrator
    working_dir: /go/src
    volumes:
      - .:/go
    networks:
      - internal

  # audit
  audit-api:
    build:
      dockerfile: ./.images/audit/api.Dockerfile
    container_name: audit-api
    networks:
      - internal
  audit-db:
    image: postgres:latest
    container_name: audit-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: audit
      POSTGRES_USER: audit
      POSTGRES_PASSWORD: audit
    volumes:
      - audit-db:/var/lib/postgresql/data
    networks:
      - internal
  audit-worker:
    build:
      dockerfile: ./.images/audit/worker.Dockerfile
    container_name: audit-worker
    networks:
      - internal

  # auth
  auth-api:
    build:
      dockerfile: ./.images/auth/api.Dockerfile
    container_name: auth-api
    networks:
      - internal
  auth-db:
    image: postgres:latest
    container_name: auth-db
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
    volumes:
      - auth-db:/var/lib/postgresql/data
    networks:
      - internal
  auth_cache:
    image: redis:latest
    container_name: auth-cache
    ports:
      - 6379:6379
    networks:
      - internal

  # queue
  queue-api:
    build:
      dockerfile: ./.images/queue/Dockerfile
    container_name: queue-api
    networks:
      - internal

volumes:
  audit-db:
    driver: local
  auth-db:
    driver: local

networks:
  internal:
    driver: bridge
