apiVersion: v1
kind: Service
metadata:
  name: queue-api
  labels:
    app.kubernetes.io/name: queue
    app.kubernetes.io/component: api
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: queue
    app.kubernetes.io/component: api
  ports:
    - name: grpc
      port: 8080
      targetPort: grpc
      appProtocol: grpc
