#!/bin/sh

cd /go/src//modules/audit/src && go test -v ./...

cd /go/src//modules/auth/src && go test -v ./...

cd /go/src//modules/queue/src && go test -v ./...

cd /go/src//modules/shared/src && go test -v ./...