{
 "title": "Go Runtime",
 "tags": [
  "go",
  "runtime"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values(go_goroutine_count, service_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutine_count{service_name=~\"$service\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Memory in use",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memory_used_bytes{service_name=~\"$service\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Memory allocations / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(go_memory_allocations_total{service_name=~\"$service\"}[1m])",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Bytes allocated / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(go_memory_allocated_bytes_total{service_name=~\"$service\"}[1m])",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "GC heap goal",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memory_gc_goal_bytes{service_name=~\"$service\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "GOGC",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_config_gogc_percent{service_name=~\"$service\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  }
 ]
}