apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: audit
resources:
  - ../../base
  - postgres.yaml
  - secret.yaml
images:
  - name: audit-api
    newTag: dev
  - name: audit-worker
    newTag: dev
  - name: migrator
    newTag: dev
