// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

// Users table for storing basic user information
type User struct {
	// Primary key for user identification
	ID int32 `json:"id"`
	// Unique login identifier
	LoginID string `json:"login_id"`
	// Hashed password
	Password string `json:"password"`
	// User email address (unique)
	Email string `json:"email"`
	// Record creation timestamp
	CreatedAt sql.NullTime `json:"created_at"`
	// Record last update timestamp
	UpdatedAt sql.NullTime `json:"updated_at"`
}

// User roles junction table - manages many-to-many relationship between users and roles
type UserRole struct {
	// User ID (composite primary key)
	UserID int32 `json:"user_id"`
	// Role ID (foreign key)
	RoleID int32 `json:"role_id"`
	// Record creation timestamp
	CreatedAt sql.NullTime `json:"created_at"`
	// Record last update timestamp
	UpdatedAt sql.NullTime `json:"updated_at"`
}

// User role types table - defines available system roles
type UserRoleType struct {
	// Primary key for role identification
	ID int32 `json:"id"`
	// Role name (admin, user, etc.)
	Role string `json:"role"`
	// Record creation timestamp
	CreatedAt sql.NullTime `json:"created_at"`
	// Record last update timestamp
	UpdatedAt sql.NullTime `json:"updated_at"`
}

// User scopes junction table - manages many-to-many relationship between users and scopes
type UserScope struct {
	// User ID (composite primary key)
	UserID int32 `json:"user_id"`
	// Scope ID (foreign key)
	ScopeID int32 `json:"scope_id"`
	// Record creation timestamp
	CreatedAt sql.NullTime `json:"created_at"`
	// Record last update timestamp
	UpdatedAt sql.NullTime `json:"updated_at"`
}

// User scope types table - defines available permission scopes in the system
type UserScopeType struct {
	// Primary key for scope identification
	ID int32 `json:"id"`
	// Scope name (read, write, etc.)
	Scope string `json:"scope"`
	// Record creation timestamp
	CreatedAt sql.NullTime `json:"created_at"`
	// Record last update timestamp
	UpdatedAt sql.NullTime `json:"updated_at"`
}
