services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace/main:cached
    command: sleep infinity
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
      queue:
        condition: service_healthy
  db:
    image: postgres:18
    volumes:
      - pg-data:/var/lib/postgresql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  cache:
    image: redis:alpine
    volumes:
      - cache-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  # elasticmq
  queue:
    image: softwaremill/elasticmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9324/health"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg-data:
  cache-data: