apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: queue
resources:
  - ../../base
  - authorization-policy.yaml
images:
  - name: queue-api
    newTag: prd
patches:
  - target:
      kind: Deployment
      name: queue-api
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
