apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth
resources:
  - ../../base
  - postgres.yaml
  - redis.yaml
  - secret.yaml
images:
  - name: auth-api
    newTag: dev
  - name: migrator
    newTag: dev
