apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: audit-api
  labels:
    app.kubernetes.io/name: audit
    app.kubernetes.io/component: api
    app.kubernetes.io/managed-by: kustomize
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: audit
      app.kubernetes.io/component: api
