apiVersion: v1
kind: Service
metadata:
  name: auth-api
  labels:
    app.kubernetes.io/name: auth
    app.kubernetes.io/component: api
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: auth
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8080
      targetPort: http
