apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: auth-api
  labels:
    app.kubernetes.io/name: auth
    app.kubernetes.io/component: api
    app.kubernetes.io/managed-by: kustomize
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: auth
      app.kubernetes.io/component: api
